import type { Campaign } from "./types";

const DAY = 24 * 60 * 60 * 1000;
const now = Date.now();

export const demoCampaigns: Campaign[] = [
  {
    id: "demo-open-web",
    slug: "open-web-jackpot",
    title: "The Open Web Jackpot",
    description:
      "A crisp puzzle about protocols, public goods, and the tiny pieces that make the open web work.",
    sponsorName: "Open Web Collective",
    sponsorMark: "OW",
    theme: "The open web",
    state: "active",
    visibility: "public",
    opensAt: new Date(now - DAY).toISOString(),
    expiresAt: new Date(now + 3 * DAY + 7 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(now - 2 * DAY).toISOString(),
    reward: {
      type: "token",
      amount: "75.00",
      symbol: "USDC",
      decimals: 6,
      escrowAccount: "crossword-v2.near",
      fundingRail: "intents",
      originLabel: "Funded with ETH on Base",
    },
    puzzle: {
      rows: 9,
      columns: 9,
      entries: [
        {
          number: 1,
          row: 0,
          column: 2,
          length: 6,
          direction: "across",
          clue: "A system anyone can inspect and improve",
        },
        {
          number: 2,
          row: 0,
          column: 5,
          length: 6,
          direction: "down",
          clue: "A value passed between independent services",
        },
        {
          number: 3,
          row: 2,
          column: 1,
          length: 7,
          direction: "across",
          clue: "A compact proof that something happened",
        },
        {
          number: 4,
          row: 2,
          column: 3,
          length: 7,
          direction: "down",
          clue: "A route chosen for the result, not the rails",
        },
        {
          number: 5,
          row: 4,
          column: 0,
          length: 6,
          direction: "across",
          clue: "A shared place where code can keep promises",
        },
        {
          number: 6,
          row: 6,
          column: 2,
          length: 7,
          direction: "across",
          clue: "What a sponsor locks before the first solve",
        },
      ],
    },
    rules: [
      "Free to play. No purchase is required.",
      "The first valid completed solution wins.",
      "The winner chooses a supported payout asset and network.",
    ],
    solverCount: 186,
    evidence: [
      {
        label: "Escrow",
        value: "75.00 USDC reserved",
      },
      {
        label: "Funding route",
        value: "Base ETH → NEAR USDC",
      },
      {
        label: "Content",
        value: "sha256:8e71…42bd",
      },
    ],
    verification: {
      status: "preview",
      fundedAndLocked: false,
      contractMatchesLedger: false,
      contractState: null,
      contractExplorerUrl: null,
      fundingTransactionExplorerUrl: null,
    },
    contentHash: "8e71f5e117be6b66c194f960a3053408453242bd",
    contractId: "crossword-v2.near",
    isDemo: true,
  },
  {
    id: "demo-agents",
    slug: "agents-have-entered-the-chat",
    title: "Agents Have Entered the Chat",
    description:
      "Human clues, machine-speed payments. A playful tour through autonomous commerce.",
    sponsorName: "The Agent Economy",
    sponsorMark: "AE",
    theme: "Agents and payments",
    state: "active",
    visibility: "public",
    opensAt: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(now + 6 * DAY).toISOString(),
    createdAt: new Date(now - DAY).toISOString(),
    reward: {
      type: "token",
      amount: "40.20",
      symbol: "USDC",
      decimals: 6,
      escrowAccount: "crossword-v2.near",
      fundingRail: "mpp",
      originLabel: "Created with x402 · funded via Intents",
    },
    puzzle: {
      rows: 8,
      columns: 8,
      entries: [
        {
          number: 1,
          row: 0,
          column: 1,
          length: 6,
          direction: "across",
          clue: "A job an autonomous program can carry out",
        },
        {
          number: 2,
          row: 0,
          column: 4,
          length: 7,
          direction: "down",
          clue: "Evidence that a payment really settled",
        },
        {
          number: 3,
          row: 2,
          column: 0,
          length: 7,
          direction: "across",
          clue: "The desired result of a chain-abstracted request",
        },
        {
          number: 4,
          row: 2,
          column: 2,
          length: 6,
          direction: "down",
          clue: "A finite permission, safer than a master key",
        },
        {
          number: 5,
          row: 5,
          column: 1,
          length: 7,
          direction: "across",
          clue: "What HTTP 402 asks the client to provide",
        },
      ],
    },
    rules: [
      "Free to play. AI agents and humans are welcome.",
      "One reward; the first valid proof claims it.",
      "Prize value is locked independently of the x402 creation fee.",
    ],
    solverCount: 92,
    evidence: [
      {
        label: "Escrow",
        value: "40.20 USDC reserved",
      },
      {
        label: "AI creation",
        value: "x402 receipt: demo…19f2",
      },
      {
        label: "Content",
        value: "sha256:b426…d7a1",
      },
    ],
    verification: {
      status: "preview",
      fundedAndLocked: false,
      contractMatchesLedger: false,
      contractState: null,
      contractExplorerUrl: null,
      fundingTransactionExplorerUrl: null,
    },
    contentHash: "b4262238d25b87cd32582bd3d4f3d97fbd44d7a1",
    contractId: "crossword-v2.near",
    isDemo: true,
  },
  {
    id: "demo-climate",
    slug: "small-planet-big-ideas",
    title: "Small Planet, Big Ideas",
    description:
      "A climate-tech crossword celebrating builders with practical, optimistic answers.",
    sponsorName: "Planetary Commons",
    sponsorMark: "PC",
    theme: "Climate technology",
    state: "scheduled",
    visibility: "public",
    opensAt: new Date(now + DAY).toISOString(),
    expiresAt: new Date(now + 8 * DAY).toISOString(),
    createdAt: new Date(now - 2 * DAY).toISOString(),
    reward: {
      type: "token",
      amount: "100.00",
      symbol: "USDC",
      decimals: 6,
      escrowAccount: "crossword-v2.near",
      fundingRail: "direct",
      originLabel: "Funded with USDC on NEAR",
    },
    puzzle: {
      rows: 8,
      columns: 8,
      entries: [
        {
          number: 1,
          row: 0,
          column: 0,
          length: 7,
          direction: "across",
          clue: "Energy replenished on a human timescale",
        },
        {
          number: 2,
          row: 0,
          column: 3,
          length: 6,
          direction: "down",
          clue: "A measurable unit avoided or removed",
        },
        {
          number: 3,
          row: 3,
          column: 1,
          length: 7,
          direction: "across",
          clue: "Designing so materials can be used again",
        },
        {
          number: 4,
          row: 1,
          column: 6,
          length: 7,
          direction: "down",
          clue: "The shared resource climate work protects",
        },
      ],
    },
    rules: [
      "The puzzle opens after the published countdown.",
      "Free to play; first valid completed solution wins.",
      "The sponsor can cancel only before opening.",
    ],
    solverCount: 0,
    evidence: [
      {
        label: "Escrow",
        value: "100.00 USDC reserved",
      },
      {
        label: "Funding route",
        value: "Direct NEAR transfer",
      },
      {
        label: "Content",
        value: "sha256:39ce…0a28",
      },
    ],
    verification: {
      status: "preview",
      fundedAndLocked: false,
      contractMatchesLedger: false,
      contractState: null,
      contractExplorerUrl: null,
      fundingTransactionExplorerUrl: null,
    },
    contentHash: "39cece02186ac6148e87586120e6d03288460a28",
    contractId: "crossword-v2.near",
    isDemo: true,
  },
];

export function getDemoCampaign(slug: string): Campaign | null {
  return demoCampaigns.find((campaign) => campaign.slug === slug) ?? null;
}
